# Author: Patan Musthakheem
# Licence: Apache 2.0
# Version: 0.1 Beta
# Stub File For bl.py

class BushBP:
    def __init__(self, key: bytes) -> None: ...

    def encrypt(self, data: bytes) -> bytes: ...

    def decrypt(self, data: bytes) -> bytes: ...

    def __encryptor(self, key: bytes, data: bytes) -> bytes: ...

    def __decryptor(self, data: bytes) -> bytes: ...

    @classmethod
    def generate_key(cls) -> bytes: ...

    @staticmethod
    def __padder(data: bytes) -> bytes: ...

    @staticmethod
    def __unpadder(data: bytes) -> bytes: ...

    @staticmethod
    def __finalize(signed_data: bytes, cipher_text: bytes, iv: bytes) -> bytes: ...

    @staticmethod
    def __check_signature(data: bytes, prev_key: bytes, key: bytes) -> bytes: ...