[tool.poetry]
name = "tox-demo"
version = "0.1.0"
description = "A demo for tox, pyproject, wheel, setuptools"
authors = ["mog <mo.gao@foxmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
wheel = "^0.36.2"
setuptools = "^57.1.0"
tox = "^3.23.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true
