[tool.poetry]
name = "arcadezero"
version = "0.0.1"
license="MIT"
description = "A beginner friendly layer on top of Arcade to create your very first game"
authors = ["Maic Siemering <maic@siemering.tech>"]
homepage = "https://github.com/eruvanos/arcadezero"
repository = "https://github.com/eruvanos/arcadezero"
readme = "README.md"
keywords = ["arcade", "beginner"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Games/Entertainment :: Arcade",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.8"
arcade = "^2.5.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
