# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ActivityEventSubcategoryChild(Model):
    """ActivityEventSubcategoryChild.

    :param subcategory_id:
    :type subcategory_id: str
    :param subcategory_code:
    :type subcategory_code: str
    :param subcategory_name:
    :type subcategory_name: str
    """

    _attribute_map = {
        'subcategory_id': {'key': 'SubcategoryId', 'type': 'str'},
        'subcategory_code': {'key': 'SubcategoryCode', 'type': 'str'},
        'subcategory_name': {'key': 'SubcategoryName', 'type': 'str'},
    }

    def __init__(self, *, subcategory_id: str=None, subcategory_code: str=None, subcategory_name: str=None, **kwargs) -> None:
        super(ActivityEventSubcategoryChild, self).__init__(**kwargs)
        self.subcategory_id = subcategory_id
        self.subcategory_code = subcategory_code
        self.subcategory_name = subcategory_name
