# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ActivityEventCategoryRelationshipResponse(Model):
    """ActivityEventCategoryRelationshipResponse.

    All required parameters must be populated in order to send to Azure.

    :param id: Required.
    :type id: str
    :param relationship_type: Required. Possible values include: 'Parent',
     'Preceding'
    :type relationship_type: str or ~smartdiagnostics_sdk.models.enum
    :param from_category: Required.
    :type from_category:
     ~smartdiagnostics_sdk.models.ActivityEventCategoryChild
    :param to_category: Required.
    :type to_category: ~smartdiagnostics_sdk.models.ActivityEventCategoryChild
    """

    _validation = {
        'id': {'required': True},
        'relationship_type': {'required': True},
        'from_category': {'required': True},
        'to_category': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'Id', 'type': 'str'},
        'relationship_type': {'key': 'RelationshipType', 'type': 'str'},
        'from_category': {'key': 'FromCategory', 'type': 'ActivityEventCategoryChild'},
        'to_category': {'key': 'ToCategory', 'type': 'ActivityEventCategoryChild'},
    }

    def __init__(self, *, id: str, relationship_type, from_category, to_category, **kwargs) -> None:
        super(ActivityEventCategoryRelationshipResponse, self).__init__(**kwargs)
        self.id = id
        self.relationship_type = relationship_type
        self.from_category = from_category
        self.to_category = to_category
