# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ActivityEventHierarchyGroupRequest(Model):
    """ActivityEventHierarchyGroupRequest.

    All required parameters must be populated in order to send to Azure.

    :param start_date_time: Required.
    :type start_date_time: datetime
    :param end_date_time: Required.
    :type end_date_time: datetime
    :param indicator_ids:
    :type indicator_ids: list[str]
    :param group_ids:
    :type group_ids: list[str]
    :param category_ids:
    :type category_ids: list[int]
    :param category_flags:
    :type category_flags: list[str]
    :param activity_line_enabled:
    :type activity_line_enabled: bool
    :param location_id:
    :type location_id: str
    """

    _validation = {
        'start_date_time': {'required': True},
        'end_date_time': {'required': True},
    }

    _attribute_map = {
        'start_date_time': {'key': 'StartDateTime', 'type': 'iso-8601'},
        'end_date_time': {'key': 'EndDateTime', 'type': 'iso-8601'},
        'indicator_ids': {'key': 'IndicatorIds', 'type': '[str]'},
        'group_ids': {'key': 'GroupIds', 'type': '[str]'},
        'category_ids': {'key': 'CategoryIds', 'type': '[int]'},
        'category_flags': {'key': 'CategoryFlags', 'type': '[str]'},
        'activity_line_enabled': {'key': 'ActivityLineEnabled', 'type': 'bool'},
        'location_id': {'key': 'LocationId', 'type': 'str'},
    }

    def __init__(self, *, start_date_time, end_date_time, indicator_ids=None, group_ids=None, category_ids=None, category_flags=None, activity_line_enabled: bool=None, location_id: str=None, **kwargs) -> None:
        super(ActivityEventHierarchyGroupRequest, self).__init__(**kwargs)
        self.start_date_time = start_date_time
        self.end_date_time = end_date_time
        self.indicator_ids = indicator_ids
        self.group_ids = group_ids
        self.category_ids = category_ids
        self.category_flags = category_flags
        self.activity_line_enabled = activity_line_enabled
        self.location_id = location_id
