# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class AnalyticsModelUpdateRequest(Model):
    """AnalyticsModelUpdateRequest.

    All required parameters must be populated in order to send to Azure.

    :param is_deprecated: Required.
    :type is_deprecated: bool
    :param triggers:
    :type triggers: list[~smartdiagnostics_sdk.models.TriggerChild]
    :param tag_ids:
    :type tag_ids: list[str]
    """

    _validation = {
        'is_deprecated': {'required': True},
    }

    _attribute_map = {
        'is_deprecated': {'key': 'IsDeprecated', 'type': 'bool'},
        'triggers': {'key': 'Triggers', 'type': '[TriggerChild]'},
        'tag_ids': {'key': 'TagIds', 'type': '[str]'},
    }

    def __init__(self, **kwargs):
        super(AnalyticsModelUpdateRequest, self).__init__(**kwargs)
        self.is_deprecated = kwargs.get('is_deprecated', None)
        self.triggers = kwargs.get('triggers', None)
        self.tag_ids = kwargs.get('tag_ids', None)
