# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IndicatorOptionsResponse(Model):
    """IndicatorOptionsResponse.

    :param measure_of_codes:
    :type measure_of_codes:
     list[~smartdiagnostics_sdk.models.IndicatorMeasureOfCodeChild]
    """

    _attribute_map = {
        'measure_of_codes': {'key': 'MeasureOfCodes', 'type': '[IndicatorMeasureOfCodeChild]'},
    }

    def __init__(self, *, measure_of_codes=None, **kwargs) -> None:
        super(IndicatorOptionsResponse, self).__init__(**kwargs)
        self.measure_of_codes = measure_of_codes
