# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class JobUploadErrorResponse(Model):
    """JobUploadErrorResponse.

    All required parameters must be populated in order to send to Azure.

    :param errors: Required.
    :type errors: list[str]
    :param status_code: Required.
    :type status_code: int
    """

    _validation = {
        'errors': {'required': True},
        'status_code': {'required': True},
    }

    _attribute_map = {
        'errors': {'key': 'Errors', 'type': '[str]'},
        'status_code': {'key': 'StatusCode', 'type': 'int'},
    }

    def __init__(self, **kwargs):
        super(JobUploadErrorResponse, self).__init__(**kwargs)
        self.errors = kwargs.get('errors', None)
        self.status_code = kwargs.get('status_code', None)
