# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SessionSelectedPointChild(Model):
    """SessionSelectedPointChild.

    :param xvalue:
    :type xvalue: int
    :param series_id:
    :type series_id: str
    """

    _attribute_map = {
        'xvalue': {'key': 'XValue', 'type': 'int'},
        'series_id': {'key': 'SeriesId', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(SessionSelectedPointChild, self).__init__(**kwargs)
        self.xvalue = kwargs.get('xvalue', None)
        self.series_id = kwargs.get('series_id', None)
