# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UserRequestLocationChild(Model):
    """UserRequestLocationChild.

    All required parameters must be populated in order to send to Azure.

    :param location_id: Required. Location Id
    :type location_id: str
    :param location_user_role: Required. User role. Must be one of the
     following:
     - AccountAdmin
     - ApplicationUser
     - Technician
     - User. Possible values include: 'Invalid', 'SaasAdmin', 'AccountAdmin',
     'ApplicationUser', 'Technician', 'User', 'SystemProcess', 'Sentry',
     'Sales', 'CorporationAdmin', 'CorporationUser', 'CorporationNone'
    :type location_user_role: str or ~smartdiagnostics_sdk.models.enum
    """

    _validation = {
        'location_id': {'required': True},
        'location_user_role': {'required': True},
    }

    _attribute_map = {
        'location_id': {'key': 'LocationId', 'type': 'str'},
        'location_user_role': {'key': 'LocationUserRole', 'type': 'str'},
    }

    def __init__(self, *, location_id: str, location_user_role, **kwargs) -> None:
        super(UserRequestLocationChild, self).__init__(**kwargs)
        self.location_id = location_id
        self.location_user_role = location_user_role
