# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class UserPhoneNumberConfirmRequest(Model):
    """UserPhoneNumberConfirmRequest.

    All required parameters must be populated in order to send to Azure.

    :param phone_number: Required.
    :type phone_number: str
    """

    _validation = {
        'phone_number': {'required': True, 'pattern': r'\(\d{3}\)\s\d{3}-\d{4}'},
    }

    _attribute_map = {
        'phone_number': {'key': 'PhoneNumber', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(UserPhoneNumberConfirmRequest, self).__init__(**kwargs)
        self.phone_number = kwargs.get('phone_number', None)
