[tool.poetry]
name = "pytest_addons_test"
version = "1.0.6"
description = "用于测试pytest的插件"
authors = ["lin"]
packages = [
    { include = "pytest_addons_test"},
]
[tool.poetry.plugins] # Optional super table

[tool.poetry.plugins."blogtool.parsers"]
".pytest11" = "pytest_addons_test:main"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
