[tool.poetry]
name = "wikiusers-cli"
version = "1.2.1"
description = "The cli of the wikiusers python module"
authors = ["Eugenio Vinicio Berretta <euberdeveloper@gmail.com>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
whaaaaat = "^0.5.2"
prompt-toolkit = "1.0.14"
wikiusers = "^1.1.0"

[tool.poetry.dev-dependencies]
pylint = "^2.9.3"
autopep8 = "^1.5.7"

[tool.poetry.scripts]
wikiusers = 'wikiusers_cli:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
