$schema: http://json-schema.org/draft-07/schema#
$id: KeyValueStore
description: |
  Common properties supported by all key-value stores.  Refer to the :ref:`driver
  documentation<key-value-store-drivers>` for the supported
  `.driver` identifiers and driver-specific properties.
type: object
properties:
  driver:
    type: string
    title: |
      Key-value store :ref:`driver identifier<key-value-store-drivers>`
  context:
    $ref: Context
    description: Specifies context resources that augment/override the parent context.
required:
- driver
