[tool.poetry]
name = "kicksaw-data-mapping-serializer"
version = "0.1.0"
description = "Reads a csv/gdoc from kicksaw-data-mapping-serializer and automatically performs serialization"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Kicksaw-Consulting/kicksaw-data-mapping-serializer"
authors = ["Alex Drozd <alex@kicksaw.com>"]
keywords = ["kicksaw", "mapping", "serializer", "salesforce"]
packages = [
    { include = 'kicksaw_data_mapping_serializer' }
]

[tool.poetry.dependencies]
python = "^3.8"
kicksaw-data-mapping-base = "^0.1.3"
jsonpath-ng = "^1.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
