
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-14T09:26:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1471d537163ff711f76e04ee6fcdb9d59517c64a",
 "version": "4.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
