version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
    executor:
      name: win/default
      shell: powershell.exe

    steps:
      - checkout
      - run:
          command: pip install --user -r requirements.txt
          name: pip requirements.txt
      - run:
          command: python ./circle_ci_test/screen_test.py
          name: ctype_screen_test
      - run:
          command: python ./circle_ci_test/keyboard_test.py
          name: keyboard_test
      - run:
          command: python ./circle_ci_test/mouse_test.py
          name: mouse_test
      - run:
          command: python ./circle_ci_test/mouse_scroll_test.py
          name: scroll_test

workflows:
  main:
    jobs:
      - build-and-test
