
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-25T13:05:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb18eff8a05f8431dcfba9390333d493b39a5b7c",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
