
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-27T05:50:31-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b031bd2b4cb75f2e2e7551be084fb57af86f8a98",
 "version": "4.5.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
