
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T22:18:55+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "49eb53be305a998d58b7f459feae26312a720ba7",
 "version": "1.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
