
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T18:27:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "8aba3ac7cd3edb87b468480d13063cd5c1e59abb",
 "version": "0.0.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
