language: python

python:
  - 3.7.1
  - 3.8
  - 3.8.6
  - 3.9
  - 3.9.1

before_install:
  - env

install:
  - pip install --upgrade pip
  - pip install coverage
  - python setup.py install
  - pip install coveralls

script:
  - nosetests --with-doctest --with-coverage --cover-tests --cover-package=pyslice --cover-branches --cover-erase

after_success:
  - coveralls
