
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-28T10:56:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "59ebe55824f8b2ddd48e8f4540b79394090e29d0",
 "version": "2021.7.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
