
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T07:09:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "095e88d20ed7412935d13426b5ccbb54b873e24a",
 "version": "1.0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
