name = 'module_path'
version = '1.0.1'
description = 'Reliably find a modules path even when running an executable.'
url = 'https://github.com/justengel/module_path'
author = 'Justin Engel'
author_email = 'jtengel08@gmail.com'
