[tool.poetry]
name = "libp"
version = "1.0.0"
description = "libp"
authors = ["Ardustri <contact@ardustri.org>"]
license = "MIT"
packages = [{include = "libp"}]

[tool.poetry.dependencies]
python = ">=3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"