[tool.poetry]
name = "pytest_addons_test"
version = "1.0.0"
description = "用于测试pytest的插件"
authors = ["lin"]

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
