# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"run_bash": "00_core.ipynb",
         "colab_setup": "00_core.ipynb",
         "mkdir_if_not_exists": "00_core.ipynb",
         "Path.mkdir_if_not_exists": "00_core.ipynb",
         "set_plt_defaults": "01_plotting.ipynb",
         "remove_ticks": "01_plotting.ipynb",
         "ends": "02_pandas.ipynb",
         "group_by_summary": "02_pandas.ipynb",
         "datetime_from_timestamp": "02_pandas.ipynb"}

modules = ["core.py",
           "plotting.py",
           "pandas.py"]

doc_url = "https://mgfrantz.github.io/dessiccate/"

git_url = "https://github.com/mgfrantz/dessiccate/tree/master/"

def custom_doc_links(name): return None
