#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pybancointer']

package_data = \
{'': ['*']}

setup(name='pybancointer',
      version='0.0.1',
      description='This module do web crawler of banco inter.',
      author='Guilherme Fabrin Franco',
      author_email='guilherme.fabrin@gmail.com',
      url='https://github.com/guifabrin/pybancointer',
      packages=packages,
      package_data=package_data,
     )
