
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T16:24:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9770e55c5f0eecc8dc6368a88d534a28c9796a87",
 "version": "0.4.64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
