
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-29T11:33:32-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a5080e3a3c76724fd8855d66f6b16326e2beb81",
 "version": "1.4.1rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
