#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['levy']

package_data = \
{'': ['*']}

setup(name='levy',
      version='0.5',
      description='Dynamic python configuration parser',
      author='pmbrull',
      author_email='peremiquelbrull@gmail.com',
      url='https://github.com/pmbrull/levy',
      packages=packages,
      package_data=package_data,
     )
