# Generated by Django 3.2.5 on 2021-07-28 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorlog_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
