
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-30T18:24:12+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "34f8c4e919296a8eb9cb55b738077ce1edbda5ae",
 "version": "1.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
