
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-31T17:25:10+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "c9f74e5df07b4a54b14b89879a7609e45b1c6e2d",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
