#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tap2shex']

package_data = \
{'': ['*']}

install_requires = \
['click',
 'dataclasses',
 'ruamel.base',
 'ruamel.yaml',
 'PyShEx',
 'PyShExC',
 'ShExJSG',
 'dctap']

extras_require = \
{'doc': ['sphinx', 'sphinx_rtd_theme'], 'test': ['pytest', 'pytest-cov']}

entry_points = \
{'console_scripts': ['tap2shex = tap2shex.cli:cli']}

setup(name='tap2shex',
      version='0.2',
      description='Generate ShEx from DCTAP instances.',
      author='Tom Baker',
      author_email='tom@tombaker.org',
      url='https://github.com/tombaker/tap2shex',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.8',
     )
