[tool.poetry]
name = "et-micc3"
version = "3.0.0"
description = "<Enter a one-sentence description of this project here.>"
authors = ["Bert Tijskens <engelbert.tijskens@uantwerpen.be>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/et-micc3"
homepage = "https://github.com/etijskens/et-micc3"

keywords = []

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.0.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
micc3 = "et_micc3:cli_micc3.main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
