[tool.poetry]
authors = ["Daniel Stahl <danstahl1138@gmail.com>"]
description = "Utilities for firebase and spark streaming specifically for streamstate"
homepage = "https://github.com/StreamState/streamstate-utils"
name = "streamstate-utils"
repository = "https://github.com/StreamState/streamstate-utils"
version = "0.13.0"

[tool.poetry.dependencies]
firebase-admin = "^5.0.0"
google-auth = "^1.29.0"
google-cloud-storage = "^1.37.1"
pydantic = "^1.8.2"
python = "^3.7"

[tool.poetry.scripts]
run-test = "streamstate_utils.run_test:main"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
codecov = "^2.1.11"
coverage = {extras = ["toml"], version = "^5.5"}
mypy = "^0.812"
pre-commit = "^2.13.0"
pyspark = "^3.1.1"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
single-source = "^0.2.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["streamstate_utils"]

[tool.coverage.report]
show_missing = true
