[tool.isort]
multi_line_output = "3"
include_trailing_comma = "True"
force_grid_wrap = "0"
use_parentheses = "True"
line_length = "88"

[tool.poetry]
name = "smoothtransitions"
version = "0.4.1"
description = ""
authors = ["Florian Roessler <smoothtransitions.github@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1"
cclib = "^1.7"
tabulate = "^0.8.9"
pandas = "^1.2.3"
matplotlib = "^3.3.4"
click = "^7.1.2"
PyYAML = "^5.4.1"
numpy = "^1.20.1"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
Sphinx = "^3.5.4"
numpydoc = "^1.1.0"
pytest = "^6.2.2"
black = "^20.8b1"
isort = "^5.7.0"
flake8 = "^3.9.1"
pre-commit = "^2.12.1"
pytest-mock = "^3.5.1"
ipython = "^7.21.0"
pytest-cov = "^2.11.1"
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
smoothtransitions = 'smoothtransitions.smoothtransitions:app'