[tool.poetry]
name = "raftel"
version = "0.3.3"
description = "package to plot s2id easily with only one line of code"
authors = ["mitbal <mit.iqi@gmail.com>"]
keywords = ["s2id", "map"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/mitbal/raftel"
repository = "https://github.com/mitbal/raftel"

[tool.poetry.dependencies]
python = "^3.7"
staticmap = "^0.5.5"
s2sphere = "^0.2.5"
seaborn = "^0.11.1"
monochromap = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
