[tool.poetry]
name = "chanml-client"
version = "0.1.1"
description = "chanml-client"
authors = ["Jun Du <dujun@ruiking.com>"]
readme = "README.md"

packages = [
    { include="cml", from="." },
]

[tool.poetry.scripts]
cml = "cml.cml:app"

[tool.poetry.dependencies]
python = "^3.7"
typer = {extras = ["all"], version = "^0.3.2"}
requests = "2.25.1"
ujson = "4.0.2"
tqdm = "4.61.2"
httpx = "0.18.2"
Pygments = "^2.9.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.7b0"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
