
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-01T05:31:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd77d506a6b883e096083aade1a2fba9a99cb239",
 "version": "1.0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
