[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "dataquality"
author = "Anthony Corletti"
author-email = "anthony@rungalileo.io"
classifiers = [ "License :: OSI Approved :: Apache Software License",]

