
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T17:24:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "05d0734e383d422437767b9a592f5c2a8e7308b9",
 "version": "0.4.66"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
