
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T11:25:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a43d0f5864854b5101d55da268ce7cbe834a87d9",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
