[tool.poetry]
name = "miom"
version = "0.9.0-alpha.0"
description = "Mixed Integer Optimization for Metabolism"
authors = ["Pablo R. Mier <pablo.rodriguez.mier@gmail.com>"]
keywords = ["optimization", "LP", "MIP", "metabolism", "metabolic-networks"]
license = "GPLv3"
include = [
	"LICENSE"
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.20.3"
mip = "^1.13.0"
picos = "^2.2.43"
gurobipy = "^9.1.2"
swiglpk = "^5.0.3"
mosek = "^9.2.47"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
mkdocs-material = "^7.2.0"
mkdocstrings = "^0.15.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
