[tool.poetry]
name = "independency"
version = "1.1"
description = "Dependency injection container"
readme = "README.md"
repository = "https://github.com/Apollon76/di"
authors = ["apollon <Apollon76@yandex.ru>", "ashibaev <ashibaev98@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^19.3b0"
flake8-awesome = "<1.3"
mypy = "^0.812"
pylint = "*"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py38']
line-length = 120

