[tool.poetry]
name = "shioajicaller"
version = "0.1.3.2"
description = "shioaj warp caller"
authors = ["Steve Lo <info@sd.idv.tw>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
shioaji = "^0.3.2.dev4"
python-dotenv = "^0.18.0"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]
shioaji = "^0.3.2.dev4"
python-dotenv = "^0.18.0"

[tool.poetry.scripts]
shioajicaller = "shioajicaller.cli:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
