""" Defaults to be loaded upon first program run or when a table is reset."""


questions = [
    'Tell me about yourself.',
    'Run through your resume for me.',
    'Why did you choose data science?',
    'Why did you switch to coding?',
    'Tell me about a time you dealt with an ambiguous situation.',
    'Where do you see yourself in five years?',
    'What kind of leadership style do you prefer?',
    'What is your greatest strength?',
    'What is a weakness you have improved?',
    'Tell me about yourself.',
    'Describe a time you had to work with a difficult coworker.',
    'Describe a time you had to work as part of a team.',
    'Tell me about a time you had to meet a strict deadline.',
    'What is your greatest weakness?',
    'What is your greatest professional achievement?',
    'Tell me about a challenge you faced at work.',
    'How would your previous bosses describe you?',
    'Tell me about a time you demonstrated leadership skills.',
    'Describe a time you had a conflict with a customer.',
    'Tell me about yourself',
    'Tell me about a time you disagreed with your boss.',
    'What type of work environment do you prefer?',
    'How do you deal with pressure or stress?',
    'What should I know that is not on your resume?',
    'Why are you the best candidate for this position?',
    'Describe your dream job.',
    'Tell me about a difficult decision you have made professionally.',
    'What do you like to do outside of work?',
    'Tell me about a time you went above and beyond.',
    'Tell me about yourself',
    'What has been your greatest failure?',
    'Discuss your resume.',
    'Discuss your education.',
    'What motivates you?',
    'What can you offer us that other candidates cannot?',
    'Tell me about one of your favorite projects that you have worked on.',
    'Tell me about a specific thing that you did that positively impacted a program or this project that you worked on.',
    'Tell me about the person you have worked with who has had the single biggest impact on you.',
    'Tell me what a productive day at work looks like for you.',
    'What has been the most challenging problem you have faced and how did you solve it?',
    'Tell me about a time when you had a conflict with a coworker,',
    'Can you tell me about a time when you have to push back on the stakeholder and what actions did you take?',
    'Do you have hobbies?'
]
default_questions = [
    {'id': i, 'question': q, 'answered': 0} for i, q in enumerate(questions)]
