# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docx_grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="docx_grpc.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0f\x64ocx_grpc.proto"+\n\nMsgRequest\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x0f\n\x07subject\x18\x02 \x01(\t"\x1a\n\x0bMsgResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t24\n\x0b\x44ocxService\x12%\n\x06GetMsg\x12\x0b.MsgRequest\x1a\x0c.MsgResponse"\x00\x62\x06proto3',
)


_MSGREQUEST = _descriptor.Descriptor(
    name="MsgRequest",
    full_name="MsgRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="MsgRequest.name",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="subject",
            full_name="MsgRequest.subject",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=19,
    serialized_end=62,
)


_MSGRESPONSE = _descriptor.Descriptor(
    name="MsgResponse",
    full_name="MsgResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="msg",
            full_name="MsgResponse.msg",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=64,
    serialized_end=90,
)

DESCRIPTOR.message_types_by_name["MsgRequest"] = _MSGREQUEST
DESCRIPTOR.message_types_by_name["MsgResponse"] = _MSGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgRequest = _reflection.GeneratedProtocolMessageType(
    "MsgRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGREQUEST,
        "__module__": "docx_grpc_pb2"
        # @@protoc_insertion_point(class_scope:MsgRequest)
    },
)
_sym_db.RegisterMessage(MsgRequest)

MsgResponse = _reflection.GeneratedProtocolMessageType(
    "MsgResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGRESPONSE,
        "__module__": "docx_grpc_pb2"
        # @@protoc_insertion_point(class_scope:MsgResponse)
    },
)
_sym_db.RegisterMessage(MsgResponse)


_DOCXSERVICE = _descriptor.ServiceDescriptor(
    name="DocxService",
    full_name="DocxService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=92,
    serialized_end=144,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetMsg",
            full_name="DocxService.GetMsg",
            index=0,
            containing_service=None,
            input_type=_MSGREQUEST,
            output_type=_MSGRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DOCXSERVICE)

DESCRIPTOR.services_by_name["DocxService"] = _DOCXSERVICE

# @@protoc_insertion_point(module_scope)
