[tool.poetry]
name = "skb"
version = "1.2.6"
description = "Synth Kit builder for Synthstrom Deluge"
authors = ["neilbaldwin <neil.baldwin@mac.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
skb = "skb.skb:main"
