
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-28T09:38:25-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cfebbe95b56b6b804487a62b83745b656f3483d",
 "version": "9.8.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
