# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://wayneouyang.github.io/causal_inference_engine/"

git_url = "https://github.com/wayneouyang/causal_inference_engine/tree/{branch}/"

def custom_doc_links(name): return None
