# This file automatically generated by
#    C:\Jenkins\workspace\python\sdk\python-scripted-build-pipeline\couchbase-python-client\couchbase_version.py
# at
#    2021-07-26 16:27:09.434952
__version__ = '3.2.0'