# Generated by Django 3.2.5 on 2021-07-26 18:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('RUB', 'Russian Ruble')], default='RUB', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='RUB', max_digits=10, verbose_name='Цена')),
                ('title', models.CharField(db_index=True, default='Услуга', help_text='наименование услуги', max_length=50, verbose_name='Наименование')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='Эта услуга позволит вам жить лучше', help_text='Описание услуги', verbose_name='Описание')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='price/images/%Y/%m/%d/', verbose_name='image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания на сервере')),
                ('status', models.CharField(choices=[('ACTIVE', 'Действующий'), ('DELETED', 'Удалено')], default='ACTIVE', help_text='Статус', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
