"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.7
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from lethean.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from lethean.exceptions import ApiAttributeError


def lazy_import():
    from lethean.model.inputs_entity import InputsEntity
    from lethean.model.output_entity import OutputEntity
    globals()['InputsEntity'] = InputsEntity
    globals()['OutputEntity'] = OutputEntity


class SearchEntity(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'block_height': (float,),  # noqa: E501
            'coinbase': (bool,),  # noqa: E501
            'confirmations': (float,),  # noqa: E501
            'current_height': (float,),  # noqa: E501
            'extra': (str,),  # noqa: E501
            'inputs': ([InputsEntity],),  # noqa: E501
            'mixin': (float,),  # noqa: E501
            'outputs': ([OutputEntity],),  # noqa: E501
            'rct_type': (float,),  # noqa: E501
            'timestamp': (float,),  # noqa: E501
            'timestamp_utc': (str,),  # noqa: E501
            'title': (str,),  # noqa: E501
            'tx_fee': (float,),  # noqa: E501
            'tx_hash': (str,),  # noqa: E501
            'tx_size': (float,),  # noqa: E501
            'tx_version': (float,),  # noqa: E501
            'xmr_inputs': (float,),  # noqa: E501
            'xmr_outputs': (float,),  # noqa: E501
            'payment_id': (str,),  # noqa: E501
            'payment_id8': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'block_height': 'block_height',  # noqa: E501
        'coinbase': 'coinbase',  # noqa: E501
        'confirmations': 'confirmations',  # noqa: E501
        'current_height': 'current_height',  # noqa: E501
        'extra': 'extra',  # noqa: E501
        'inputs': 'inputs',  # noqa: E501
        'mixin': 'mixin',  # noqa: E501
        'outputs': 'outputs',  # noqa: E501
        'rct_type': 'rct_type',  # noqa: E501
        'timestamp': 'timestamp',  # noqa: E501
        'timestamp_utc': 'timestamp_utc',  # noqa: E501
        'title': 'title',  # noqa: E501
        'tx_fee': 'tx_fee',  # noqa: E501
        'tx_hash': 'tx_hash',  # noqa: E501
        'tx_size': 'tx_size',  # noqa: E501
        'tx_version': 'tx_version',  # noqa: E501
        'xmr_inputs': 'xmr_inputs',  # noqa: E501
        'xmr_outputs': 'xmr_outputs',  # noqa: E501
        'payment_id': 'payment_id',  # noqa: E501
        'payment_id8': 'payment_id8',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, block_height, coinbase, confirmations, current_height, extra, inputs, mixin, outputs, rct_type, timestamp, timestamp_utc, title, tx_fee, tx_hash, tx_size, tx_version, xmr_inputs, xmr_outputs, *args, **kwargs):  # noqa: E501
        """SearchEntity - a model defined in OpenAPI

        Args:
            block_height (float):
            coinbase (bool):
            confirmations (float):
            current_height (float):
            extra (str):
            inputs ([InputsEntity]):
            mixin (float):
            outputs ([OutputEntity]):
            rct_type (float):
            timestamp (float):
            timestamp_utc (str):
            title (str):
            tx_fee (float):
            tx_hash (str):
            tx_size (float):
            tx_version (float):
            xmr_inputs (float):
            xmr_outputs (float):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            payment_id (str): [optional]  # noqa: E501
            payment_id8 (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.block_height = block_height
        self.coinbase = coinbase
        self.confirmations = confirmations
        self.current_height = current_height
        self.extra = extra
        self.inputs = inputs
        self.mixin = mixin
        self.outputs = outputs
        self.rct_type = rct_type
        self.timestamp = timestamp
        self.timestamp_utc = timestamp_utc
        self.title = title
        self.tx_fee = tx_fee
        self.tx_hash = tx_hash
        self.tx_size = tx_size
        self.tx_version = tx_version
        self.xmr_inputs = xmr_inputs
        self.xmr_outputs = xmr_outputs
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, block_height, coinbase, confirmations, current_height, extra, inputs, mixin, outputs, rct_type, timestamp, timestamp_utc, title, tx_fee, tx_hash, tx_size, tx_version, xmr_inputs, xmr_outputs, *args, **kwargs):  # noqa: E501
        """SearchEntity - a model defined in OpenAPI

        Args:
            block_height (float):
            coinbase (bool):
            confirmations (float):
            current_height (float):
            extra (str):
            inputs ([InputsEntity]):
            mixin (float):
            outputs ([OutputEntity]):
            rct_type (float):
            timestamp (float):
            timestamp_utc (str):
            title (str):
            tx_fee (float):
            tx_hash (str):
            tx_size (float):
            tx_version (float):
            xmr_inputs (float):
            xmr_outputs (float):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            payment_id (str): [optional]  # noqa: E501
            payment_id8 (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.block_height = block_height
        self.coinbase = coinbase
        self.confirmations = confirmations
        self.current_height = current_height
        self.extra = extra
        self.inputs = inputs
        self.mixin = mixin
        self.outputs = outputs
        self.rct_type = rct_type
        self.timestamp = timestamp
        self.timestamp_utc = timestamp_utc
        self.title = title
        self.tx_fee = tx_fee
        self.tx_hash = tx_hash
        self.tx_size = tx_size
        self.tx_version = tx_version
        self.xmr_inputs = xmr_inputs
        self.xmr_outputs = xmr_outputs
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
