[tool.poetry]
name = "temet"
version = "0.1.1"
description = ""
authors = ["cgmark101 <cgmark101@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
temet = "temet.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.3.2"}
requests = "^2.26.0"
Jinja2 = "^3.0.1"
aiofiles = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
