[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "D47calib"
author = "Mathieu Daëron"
author-email = "mathieu@daeron.fr"
home-page = "http://daeron.fr"

