[tool.poetry]
name = "aiomsa"
version = "0.1.0a8"
description = "Asynchronous xApp framework"
authors = ["Facebook Connectivity"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/facebookexternal/aiomsa"
keywords = ["xApp"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Intended Audience :: Telecommunications Industry",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Typing :: Typed",
]
include = ["LICENSE", "docs"]
exclude = ["docs/_build"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.5.4"
aiohttp-swagger = "^1.0.9"
prometheus-async = "^19.2.0"

furo = { version = "^2021.2.21b25", optional = true }
sphinx = { version = "^3.4.3", optional = true }
sphinx-autodoc-typehints = { version = "^1.11.1", optional = true }
sphinxcontrib-openapi = { version = "^0.7.0", optional = true }

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
isort = "^5.7.0"
mypy = "^0.812"
pytest = "^6.2.4"
pytest-aiohttp = "^0.3.0"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.0"

[tool.poetry.extras]
docs = ["furo", "sphinx", "sphinx-autodoc-typehints", "sphinxcontrib-openapi"]

[tool.coverage.report]
omit = ["aiomsa/abc.py"]

[tool.isort]
profile = "black"
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = true
line_length = 88
lines_after_imports = 2

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
