[tool.poetry]
name = "put_main"
version = "1.0"
description = "A set of utility classes and functions"
authors = ["Roberto Amadori"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
