# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"skimage_to_png": "01_tiling.ipynb",
         "get_savename": "01_tiling.ipynb",
         "split_cube_into_tiles": "01_tiling.ipynb",
         "convert_to_png_skimage": "01_tiling.ipynb",
         "convert_to_png_isis": "01_tiling.ipynb",
         "id_generator": "02_manifests.ipynb",
         "create_manifest": "02_manifests.ipynb",
         "merge_secret_manifest_with_ctx_index": "02_manifests.ipynb",
         "get_tile_lat_lon": "03_coordinates.ipynb",
         "process_cube_tiles": "03_coordinates.ipynb"}

modules = ["tiling.py",
           "manifests.py",
           "coordinates.py"]

doc_url = "https://michaelaye.github.io/p4_data_ingestion/"

git_url = "https://github.com/michaelaye/p4_data_ingestion/tree/main/"

def custom_doc_links(name): return None
