##
## Copyright (c) 2021, Empa, Leonie Fierz, Aaron Bojarski, Ricardo Parreira da Silva, Sven Eggimann.
##
## This file is part of CESAR-P - Combined Energy Simulation And Retrofit written in Python
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, either version 3 of the
## License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##
## Contact: https://www.empa.ch/web/s313
##

IDF_CONSTRUCTIONS_DB_ACCESS:
    FIXED_INFILTRATION_PROFILE_VALUE: 1
    INPUT_FILES:
        GLAZING_RATIO_PER_AGE_CLASS:
            PATH: "ressources/GlazingRatio.csvy"
            SEPARATOR: ";"
            LABELS:
                age_class_nr: "AgeClass"
                min: "Min"
                max: "Max"

        INFILTRATION_PER_AGE_CLASS:
            PATH: "ressources/InfiltrationRate.csvy"
            SEPARATOR: ";"
            LABELS:
                age_class_nr: "AgeClass"
                ACH_normal_pressure: 'ACH @ normal pressure'

        BUILDING_ELEMENTS:
            STANDARD_CONSTRUCTIONS_DIR: "ressources/IDFConstructions/"
            MATERIAL_PER_AGE_CLASS_IDF: "ressources/IDFConstructions/Materials.idf"
            MATERIAL_INTERNAL_IDF: "ressources/IDFConstructions/MaterialsInternalConstructions.idf"
            INTERNAL_CEILING_IDF: "ressources/IDFConstructions/InternalCeiling.idf"
            INTERNAL_FLOOR_IDF: "ressources/IDFConstructions/InternalFloor.idf"