
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T09:54:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "da4724f5de8f81bb2b158d744473993b4d9bf2c2",
 "version": "0.29.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
