steps:
  - label: "example master"
    command: .buildkite/scripts/example.sh
    plugins:
      - docker#v3.8.0:
          image: "baguasys/bagua:latest"
          propagate-environment: true
          runtime: nvidia
          network: host
    agents:
      queue: "master"
  - label: "example workers"
    parallelism: 1
    command: .buildkite/scripts/example.sh
    plugins:
      - docker#v3.8.0:
          image: "baguasys/bagua:latest"
          propagate-environment: true
          runtime: nvidia
          network: host
