[tool.poetry]
name = "openfabric-pysdk"
version = "0.1.2"
description = "Openfabric Python SDK"
authors = ["Andrei Tara <andrei@openfabric.ai>"]
readme = "README.md"
homepage = "https://openfabric.ai"
repository = "https://github.com/Openfabric/openfabic-pysdk"
keywords = ["openfabric", "SDK"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]


[tool.poetry.dependencies]
python = "^3.8"
Flask = "~=1.1.2"
Flask-RESTful = "^0.3.9"
flask-apispec = "^0.11.0"
connexion = "^2.9.0"
apispec = "~=4.4.0"
marshmallow = "~=3.11.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
