[build-system]
requires = ["flit_core >=2,<4", "requests >= 2.23.0"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "msgraph"
author = "Microsoft"
author-email = "graphtooling+python@microsoft.com"
home-page = "https://github.com/microsoftgraph/msgraph-sdk-python-core"
dist-name="msgraph-core"
requires-python=">=3.5"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

