[project]
name = "Mopidy-Async-Client"
version = "0.6.4"
license = "GNU General Public License, version 2"
readme = "README.md"
python = "^3.7"
homepage = "https://github.com/svinerus/mopidy-async-client"
repository = "https://github.com/svinerus/mopidy-async-client"

[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "mopidy_async_client"
author = "svinerus"
author-email = "svinerus@gmail.com"
home-page = "https://github.com/SvineruS/mopidy-async-client"
description-file = "README.md"
requires-python = ">=3.7"
dist-name = "mopidy-async-client"
keywords = "mopidy, mpd, async, asyncio, client, player"
requires = ["websockets"]
