
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-31T18:27:07+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "9e6347c08fa5982504b4b02fd2628e953ae3db8a",
 "version": "2.2.12.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
