from time import time

import arcade

start = time()

coin1 = arcade.Sound(":resources:sounds/coin1.wav")
coin2 = arcade.Sound(":resources:sounds/coin2.wav")
coin3 = arcade.Sound(":resources:sounds/coin3.wav")
coin4 = arcade.Sound(":resources:sounds/coin4.wav")
coin5 = arcade.Sound(":resources:sounds/coin5.wav")
error1 = arcade.Sound(":resources:sounds/error1.wav")
error2 = arcade.Sound(":resources:sounds/error2.wav")
error3 = arcade.Sound(":resources:sounds/error3.wav")
error4 = arcade.Sound(":resources:sounds/error4.wav")
error5 = arcade.Sound(":resources:sounds/error5.wav")
explosion1 = arcade.Sound(":resources:sounds/explosion1.wav")
explosion2 = arcade.Sound(":resources:sounds/explosion2.wav")
fall1 = arcade.Sound(":resources:sounds/fall1.wav")
fall2 = arcade.Sound(":resources:sounds/fall2.wav")
fall3 = arcade.Sound(":resources:sounds/fall3.wav")
fall4 = arcade.Sound(":resources:sounds/fall4.wav")
gameover1 = arcade.Sound(":resources:sounds/gameover1.wav")
gameover2 = arcade.Sound(":resources:sounds/gameover2.wav")
gameover3 = arcade.Sound(":resources:sounds/gameover3.wav")
gameover4 = arcade.Sound(":resources:sounds/gameover4.wav")
gameover5 = arcade.Sound(":resources:sounds/gameover5.wav")
hit1 = arcade.Sound(":resources:sounds/hit1.wav")
hit2 = arcade.Sound(":resources:sounds/hit2.wav")
hit3 = arcade.Sound(":resources:sounds/hit3.wav")
hit4 = arcade.Sound(":resources:sounds/hit4.wav")
hit5 = arcade.Sound(":resources:sounds/hit5.wav")
hurt1 = arcade.Sound(":resources:sounds/hurt1.wav")
hurt2 = arcade.Sound(":resources:sounds/hurt2.wav")
hurt3 = arcade.Sound(":resources:sounds/hurt3.wav")
hurt4 = arcade.Sound(":resources:sounds/hurt4.wav")
hurt5 = arcade.Sound(":resources:sounds/hurt5.wav")
jump1 = arcade.Sound(":resources:sounds/jump1.wav")
jump2 = arcade.Sound(":resources:sounds/jump2.wav")
jump3 = arcade.Sound(":resources:sounds/jump3.wav")
jump4 = arcade.Sound(":resources:sounds/jump4.wav")
jump5 = arcade.Sound(":resources:sounds/jump5.wav")
laser1 = arcade.Sound(":resources:sounds/laser1.wav")
laser2 = arcade.Sound(":resources:sounds/laser2.wav")
laser3 = arcade.Sound(":resources:sounds/laser3.wav")
laser4 = arcade.Sound(":resources:sounds/laser4.wav")
laser5 = arcade.Sound(":resources:sounds/laser5.wav")
lose1 = arcade.Sound(":resources:sounds/lose1.wav")
lose2 = arcade.Sound(":resources:sounds/lose2.wav")
lose3 = arcade.Sound(":resources:sounds/lose3.wav")
lose4 = arcade.Sound(":resources:sounds/lose4.wav")
lose5 = arcade.Sound(":resources:sounds/lose5.wav")
phaseJump1 = arcade.Sound(":resources:sounds/phaseJump1.wav")
rockHit2 = arcade.Sound(":resources:sounds/rockHit2.wav")
secret2 = arcade.Sound(":resources:sounds/secret2.wav")
secret4 = arcade.Sound(":resources:sounds/secret4.wav")
upgrade1 = arcade.Sound(":resources:sounds/upgrade1.wav")
upgrade2 = arcade.Sound(":resources:sounds/upgrade2.wav")
upgrade3 = arcade.Sound(":resources:sounds/upgrade3.wav")
upgrade4 = arcade.Sound(":resources:sounds/upgrade4.wav")
upgrade5 = arcade.Sound(":resources:sounds/upgrade5.wav")

coin2.play(0)  # play sound silent to reduce first play time
