
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-07-30T11:02:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4ebc9189e1c82a6abf07d5d5ae7ad4efe2ae20c",
 "version": "5.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
