
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T03:42:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9f7562b7b0c3e2826de4eea6fb7df9b835a65c99",
 "version": "2.4.0dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
