
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2021-07-24T19:29:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c6e2c3a28a3493bd7040935bc729ea6ed4e6260",
 "version": "v0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
