
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T16:07:47+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "064f1eb985fdaff49b1426266a7f1dc0aac0cd0c",
 "version": "0.2.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
