#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['requests >=2.25']

setup(name='soundsliceapi',
      version='1.0',
      description="The official Python library for Soundslice's data API.",
      author='Soundslice',
      author_email='feedback@soundslice.com',
      url='https://github.com/soundslice/soundsliceapi/',
      py_modules=['soundsliceapi'],
      install_requires=install_requires,
     )
