[tool.poetry]
name = "beau-pyrm"
version = "0.1.0"
description = "Very simple relationship manager written in Python."
authors = ["Beau Hilton <beau.hilton@vumc.org>"]
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
beau-pyrm = "beau_pyrm.main:app"

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.6.0"
typer = {extras = ["all"], version = "^0.3.2"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
