type: map
mapping:
  name:
    type: str
    required: True
  schema:
    required: True
    type: str
    pattern: "^(\\*|\\d+(\\.\\d+){0,2}(\\.\\*)?)$"
  datetime_format:
    required: True
    type: str
  time_format:
    required: True
    type: str
  date_format:
    required: True
    type: str
  scope_delimiter:
    required: False
    type: str
  list_delimiter:
    required: False
    type: str
  default_event_attributes:
    required: False
    type: map
    mapping:
      scopes:
        required: True
        type: seq
        range:
          min: 1
        sequence:
          - type: map
            mapping:
              name:
                unique: True
                type: str
                required: True
                pattern: "^[a-zA-Z]\\w*$"
              attributes:
                type: seq
                required: True
                range:
                  min: 1
                sequence:
                  - type: map
                    mapping:
                      name:
                        unique: True
                        type: str
                        required: True
                        pattern: "^[_a-zA-Z]\\w*$"

                      type:
                        type: str
                        pattern: "^(|list\/)(string|integer|boolean|datetime|date|time|float|map|enum\/[a-zA-Z]+)$"
                        required: True

                      value:
                        type: str
                        required: False

                      required:
                        type: bool
                        required: True

