
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-29T18:38:55-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a23e11a50f433623d643ca73301312835dc8bd68",
 "version": "1.4.1rc7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
