
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-24T10:38:31+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "532df9870d7fd0226756b2c41eaaeebbaf50a90c",
 "version": "1.77"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
