
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T10:03:16-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b8925cacf4d8bb6025dac20ce72c12ab0184843",
 "version": "4.5.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
