
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T18:16:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "11b1f0ae3da7fdd442b87cd0ebb831ef21ffaad8",
 "version": "0.0.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
