
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-23T16:32:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1855824ffd89fbc693e8cb4f7a6c2fc19768b5b",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
