
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-28T10:56:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4372d3501062f0022a942b0f220d5a67bb18a64f",
 "version": "v2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
