language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
env:
  - DJANGO_VERSION=2.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .[flake8,tests]
script:
  - flake8
  - pytest
