name: suite2p
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8,<3.9
  - pip
  - mkl
  - tbb
  - numpy
  - numba
  - matplotlib
  - scipy<1.6.3
  - scikit-learn
  - pytorch>=1.7.1
  - h5py=2.10.0
  - pip:
    - pyqt5
    - pyqt5.sip
    - natsort
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - suite2p
