# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ActivityEventCategoryChild(Model):
    """ActivityEventCategoryChild.

    :param category_id:
    :type category_id: int
    :param category_code:
    :type category_code: str
    :param category_name:
    :type category_name: str
    :param category_description:
    :type category_description: str
    :param category_owner_type: Possible values include: 'Global',
     'Application', 'Account'
    :type category_owner_type: str or ~smartdiagnostics_sdk.models.enum
    :param category_flag: Possible values include: 'None', 'Alarm', 'Warning',
     'Manual', 'Automatic', 'MachineIQ'
    :type category_flag: str or ~smartdiagnostics_sdk.models.enum
    """

    _attribute_map = {
        'category_id': {'key': 'CategoryId', 'type': 'int'},
        'category_code': {'key': 'CategoryCode', 'type': 'str'},
        'category_name': {'key': 'CategoryName', 'type': 'str'},
        'category_description': {'key': 'CategoryDescription', 'type': 'str'},
        'category_owner_type': {'key': 'CategoryOwnerType', 'type': 'str'},
        'category_flag': {'key': 'CategoryFlag', 'type': 'str'},
    }

    def __init__(self, *, category_id: int=None, category_code: str=None, category_name: str=None, category_description: str=None, category_owner_type=None, category_flag=None, **kwargs) -> None:
        super(ActivityEventCategoryChild, self).__init__(**kwargs)
        self.category_id = category_id
        self.category_code = category_code
        self.category_name = category_name
        self.category_description = category_description
        self.category_owner_type = category_owner_type
        self.category_flag = category_flag
