# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ActivityEventFieldEntryChild(Model):
    """ActivityEventFieldEntryChild.

    :param field_entry_id:
    :type field_entry_id: str
    :param field_value:
    :type field_value: str
    :param field_id:
    :type field_id: str
    :param field_code:
    :type field_code: str
    :param field_name:
    :type field_name: str
    :param field_type: Possible values include: 'String', 'Bool', 'Int',
     'Float', 'Status'
    :type field_type: str or ~smartdiagnostics_sdk.models.enum
    """

    _attribute_map = {
        'field_entry_id': {'key': 'FieldEntryId', 'type': 'str'},
        'field_value': {'key': 'FieldValue', 'type': 'str'},
        'field_id': {'key': 'FieldId', 'type': 'str'},
        'field_code': {'key': 'FieldCode', 'type': 'str'},
        'field_name': {'key': 'FieldName', 'type': 'str'},
        'field_type': {'key': 'FieldType', 'type': 'str'},
    }

    def __init__(self, *, field_entry_id: str=None, field_value: str=None, field_id: str=None, field_code: str=None, field_name: str=None, field_type=None, **kwargs) -> None:
        super(ActivityEventFieldEntryChild, self).__init__(**kwargs)
        self.field_entry_id = field_entry_id
        self.field_value = field_value
        self.field_id = field_id
        self.field_code = field_code
        self.field_name = field_name
        self.field_type = field_type
