# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ActivityEventRelationshipCreateRequest(Model):
    """ActivityEventRelationshipCreateRequest.

    All required parameters must be populated in order to send to Azure.

    :param relationship_type: Required. Possible values include: 'Parent',
     'Preceding'
    :type relationship_type: str or ~smartdiagnostics_sdk.models.enum
    :param from_activity_event_id: Required.
    :type from_activity_event_id: str
    :param to_activity_event_id: Required.
    :type to_activity_event_id: str
    """

    _validation = {
        'relationship_type': {'required': True},
        'from_activity_event_id': {'required': True},
        'to_activity_event_id': {'required': True},
    }

    _attribute_map = {
        'relationship_type': {'key': 'RelationshipType', 'type': 'str'},
        'from_activity_event_id': {'key': 'FromActivityEventId', 'type': 'str'},
        'to_activity_event_id': {'key': 'ToActivityEventId', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(ActivityEventRelationshipCreateRequest, self).__init__(**kwargs)
        self.relationship_type = kwargs.get('relationship_type', None)
        self.from_activity_event_id = kwargs.get('from_activity_event_id', None)
        self.to_activity_event_id = kwargs.get('to_activity_event_id', None)
