# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IdentityProviderCreateRequest(Model):
    """IdentityProviderCreateRequest.

    All required parameters must be populated in order to send to Azure.

    :param name: Required.
    :type name: str
    :param username_identifiers:
    :type username_identifiers: list[str]
    :param corporation_id: Required.
    :type corporation_id: str
    """

    _validation = {
        'name': {'required': True},
        'corporation_id': {'required': True},
    }

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'username_identifiers': {'key': 'UsernameIdentifiers', 'type': '[str]'},
        'corporation_id': {'key': 'CorporationId', 'type': 'str'},
    }

    def __init__(self, *, name: str, corporation_id: str, username_identifiers=None, **kwargs) -> None:
        super(IdentityProviderCreateRequest, self).__init__(**kwargs)
        self.name = name
        self.username_identifiers = username_identifiers
        self.corporation_id = corporation_id
