# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IdentityProviderResponse(Model):
    """IdentityProviderResponse.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. ID
    :type id: int
    :param name: Name
    :type name: str
    :param username_identifiers: Username Identifier
    :type username_identifiers: list[str]
    :param corporation_child:
    :type corporation_child:
     ~smartdiagnostics_sdk.models.PrimaryCorporationChild
    """

    _validation = {
        'id': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'Id', 'type': 'int'},
        'name': {'key': 'Name', 'type': 'str'},
        'username_identifiers': {'key': 'UsernameIdentifiers', 'type': '[str]'},
        'corporation_child': {'key': 'CorporationChild', 'type': 'PrimaryCorporationChild'},
    }

    def __init__(self, **kwargs):
        super(IdentityProviderResponse, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.username_identifiers = kwargs.get('username_identifiers', None)
        self.corporation_child = kwargs.get('corporation_child', None)
