# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class IndicatorResponse(Model):
    """IndicatorResponse.

    All required parameters must be populated in order to send to Azure.

    :param id: Required. The Id of the indicator
    :type id: str
    :param name: Required. The name of the indicator
    :type name: str
    :param abbreviation: The abbreviation of the indicator
    :type abbreviation: str
    :param system_sort_order: A number indicating where the indicator shows up
     in the list of indicators for a System.
    :type system_sort_order: int
    :param indicator_type: Indicates the type of the indicator. Possible
     values include: 'Temperature', 'Pressure', 'Flow', 'Humidity', 'Power',
     'DifferentialPressure', 'MultiSensorDifferentialPressure', 'Voltage',
     'GeneralizedAtoD', 'VibrationBandRms', 'VibrationBandMax',
     'VibrationOverallPeak', 'VibrationOverallRms', 'VibrationOverallSkewness',
     'VibrationOverallKurtosis', 'VibrationOverallCrestFactor',
     'DamageAccumulation', 'VibrationBandRmsAccel', 'VibrationBandMaxAccel',
     'VibrationOverallPeakAccel', 'VibrationOverallRmsAccel',
     'VibrationOverallSkewnessAccel', 'VibrationOverallKurtosisAccel',
     'VibrationOverallCrestFactorAccel', 'DamageAccumulationAccel', 'Group',
     'VibrationOverall', 'VibrationOverallAccel', 'GeneralTimeSeries', 'Math',
     'OnStatistics', 'OffStatistics', 'AlarmStatistics', 'WarningStatistics',
     'PositivePeakPressure', 'NegativePeakPressure', 'RmsPressure',
     'BandPressure', 'OnPercentStatistics', 'OffPercentStatistics',
     'AlarmPercentStatistics', 'WarningPercentStatistics', 'SignalStrength',
     'RunningSpeed', 'DamageAccumulationPressure', 'OilHumidity',
     'OilTemperature', 'DamageAccumulationAccelRaw', 'ThermalRegionOfInterest',
     'SmartMetric', 'Feature'
    :type indicator_type: str or ~smartdiagnostics_sdk.models.enum
    :param measure_of: Indicates what the sensor measures. Possible values
     include: 'Invalid', 'CurrentPhaseA', 'PeakCurrentPhaseA', 'CurrentPhaseB',
     'PeakCurrentPhaseB', 'CurrentPhaseC', 'PeakCurrentPhaseC',
     'DifferentialPressure', 'Flow', 'Humidity', 'NodeTemperature',
     'NodeVoltage', 'PeakVibration', 'Pressure', 'RmsVibration',
     'SignalStrength', 'StandardAirVelocity', 'SupplyVoltage', 'Temperature',
     'TotalCurrent', 'VibrationXAxis', 'VibrationYAxis', 'Voltage', 'Current',
     'AtoDChannel1', 'AtoDChannel2', 'AtoDChannel3', 'AtoDChannel4',
     'AtoDChannel5', 'AtoDChannel6', 'OilTemperature', 'OilHumidity', 'X', 'Y',
     'Z', 'Custom', 'WirelessEfficiency', 'PacketSuccessRate', 'NodeHumidity',
     'BurstSuccessRate'
    :type measure_of: str or ~smartdiagnostics_sdk.models.enum
    :param display_units: The short hand form of the `BaseUnit` used for the
     display (g, °C, mm/sec)
    :type display_units: str
    :param base_units: The full name of the Unit (G-Force, Celsius,
     MillimetersperSec)
    :type base_units: str
    :param has_spectrum: Whether or not the indicator produces burst data that
     can be plotted
     on a spectrum chart (the frequency or time wave spectrum's)
    :type has_spectrum: bool
    :param meta_data:
    :type meta_data: str
    :param damage_exponent:
    :type damage_exponent: int
    :param hierarchy:
    :type hierarchy: list[~smartdiagnostics_sdk.models.HierarchyChild]
    :param alarm_definition:
    :type alarm_definition: ~smartdiagnostics_sdk.models.AlarmDefinitionChild
    :param band_definition:
    :type band_definition: ~smartdiagnostics_sdk.models.BandDefinitionChild
    :param baseline:
    :type baseline: ~smartdiagnostics_sdk.models.BaselineIndicatorChild
    """

    _validation = {
        'id': {'required': True},
        'name': {'required': True},
    }

    _attribute_map = {
        'id': {'key': 'Id', 'type': 'str'},
        'name': {'key': 'Name', 'type': 'str'},
        'abbreviation': {'key': 'Abbreviation', 'type': 'str'},
        'system_sort_order': {'key': 'SystemSortOrder', 'type': 'int'},
        'indicator_type': {'key': 'IndicatorType', 'type': 'str'},
        'measure_of': {'key': 'MeasureOf', 'type': 'str'},
        'display_units': {'key': 'DisplayUnits', 'type': 'str'},
        'base_units': {'key': 'BaseUnits', 'type': 'str'},
        'has_spectrum': {'key': 'HasSpectrum', 'type': 'bool'},
        'meta_data': {'key': 'MetaData', 'type': 'str'},
        'damage_exponent': {'key': 'DamageExponent', 'type': 'int'},
        'hierarchy': {'key': 'Hierarchy', 'type': '[HierarchyChild]'},
        'alarm_definition': {'key': 'AlarmDefinition', 'type': 'AlarmDefinitionChild'},
        'band_definition': {'key': 'BandDefinition', 'type': 'BandDefinitionChild'},
        'baseline': {'key': 'Baseline', 'type': 'BaselineIndicatorChild'},
    }

    def __init__(self, **kwargs):
        super(IndicatorResponse, self).__init__(**kwargs)
        self.id = kwargs.get('id', None)
        self.name = kwargs.get('name', None)
        self.abbreviation = kwargs.get('abbreviation', None)
        self.system_sort_order = kwargs.get('system_sort_order', None)
        self.indicator_type = kwargs.get('indicator_type', None)
        self.measure_of = kwargs.get('measure_of', None)
        self.display_units = kwargs.get('display_units', None)
        self.base_units = kwargs.get('base_units', None)
        self.has_spectrum = kwargs.get('has_spectrum', None)
        self.meta_data = kwargs.get('meta_data', None)
        self.damage_exponent = kwargs.get('damage_exponent', None)
        self.hierarchy = kwargs.get('hierarchy', None)
        self.alarm_definition = kwargs.get('alarm_definition', None)
        self.band_definition = kwargs.get('band_definition', None)
        self.baseline = kwargs.get('baseline', None)
