# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MonitoringPointChild(Model):
    """MonitoringPointChild.

    All required parameters must be populated in order to send to Azure.

    :param monitoring_point_id: Required. Monitoring Point Id
    :type monitoring_point_id: str
    :param monitoring_point_name: Required. Monitoring Point Name
    :type monitoring_point_name: str
    :param monitoring_point_abbreviation: Monitoring Point Abbreviation
    :type monitoring_point_abbreviation: str
    :param monitoring_point_type: Required. Monitoring Point Type. Possible
     values include: 'Custom', 'Vibration', 'Pressure', 'OilQuality',
     'GeneralInput', 'IndicatorBased', 'GeneralAtoD'
    :type monitoring_point_type: str or ~smartdiagnostics_sdk.models.enum
    """

    _validation = {
        'monitoring_point_id': {'required': True},
        'monitoring_point_name': {'required': True},
        'monitoring_point_type': {'required': True},
    }

    _attribute_map = {
        'monitoring_point_id': {'key': 'MonitoringPointId', 'type': 'str'},
        'monitoring_point_name': {'key': 'MonitoringPointName', 'type': 'str'},
        'monitoring_point_abbreviation': {'key': 'MonitoringPointAbbreviation', 'type': 'str'},
        'monitoring_point_type': {'key': 'MonitoringPointType', 'type': 'str'},
    }

    def __init__(self, *, monitoring_point_id: str, monitoring_point_name: str, monitoring_point_type, monitoring_point_abbreviation: str=None, **kwargs) -> None:
        super(MonitoringPointChild, self).__init__(**kwargs)
        self.monitoring_point_id = monitoring_point_id
        self.monitoring_point_name = monitoring_point_name
        self.monitoring_point_abbreviation = monitoring_point_abbreviation
        self.monitoring_point_type = monitoring_point_type
