
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-27T05:09:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a94043c21249d81aa4c0892a7c8680c2f9eecf93",
 "version": "4.7.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
