name: Code Style

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  clang-format:

    name: "clang-format"
    runs-on: ubuntu-latest

    steps:

      - name: "🔀 Checkout repository"
        uses: actions/checkout@v2

      - name: "⬇️️ Install dependencies"
        run: sudo apt-get install -y --no-install-recommends colordiff

      - name: "📝 Format C++"
        uses: diegoferigo/gh-action-clang-format@v0.1
        id: format
        with:
          style: file
          pattern: |
            *.h
            *.cpp

      - name: "🔍️ Inspect style diff"
        if: failure()
        run: printf "${{ steps.format.outputs.diff }}" | colordiff
