[tool.poetry]
name = "taskw_gcal_sync"
version = "v0.7.0"
description = "Taskwarrior <-> Google Calendar synchronisation tool"
license = "MIT"
authors = ["Nikos Koukis <nickkouk@gmail.com>", ]
readme = "README.md"
homepage = "https://github.com/bergercookie/taskw_gcal_sync"
repository = "https://github.com/bergercookie/taskw_gcal_sync"
classifiers = [ "Programming Language :: Python",
                "Programming Language :: Python :: 3",
                "Programming Language :: Python :: 3.8",
                "Programming Language :: Python :: 3.9",
                "Programming Language :: Python :: 3 :: Only",
                "Intended Audience :: Developers",
                "Natural Language :: English",
                "License :: OSI Approved :: MIT License",
                "Environment :: Console",
                "Operating System :: Unix",
                "Topic :: Utilities", ]

[tool.poetry.dependencies]
python = "^3.8"

PyYAML = "^5.4.1"
bidict = "^0.21.2"
click = "^8.0"
colored-traceback = "^0.3.0"
colorlog = "^4.8.0"
google-api-python-client = "^2.1.0"
google-auth-oauthlib = "^0.4.4"
loguru = "^0.5.3"
overrides = "^3.1.0"
python-dateutil = "^2.8.1"
pytz = "^2021.1"
rfc3339 = "^6.2"
sh = "^1.14.1"
tqdm = "^4.61.2"
typing = "^3.7.4"
taskw = "^1.3.0"

[tool.poetry.dev-dependencies]
black = "21.7b0"
isort = ">=5.8.0"
mypy = "^0.812"
pdbpp = "^0.10.3"
pylint = ">=2.9"
pytest = "^6.2.3"
rope = "^0.19"
# taskw = { git="https://github.com/bergercookie/taskw.git", branch="develop" }

[tool.poetry.scripts]
tw_gcal_sync = "taskw_gcal_sync.scripts.tw_gcal_sync:main"

[tool.isort]
line_length = 95
include_trailing_comma = true
multi_line_output = 3

[tool.black]
experimental-string-processing = true
line-length = 95
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

