
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T08:48:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ec0ea23dc24c83e5370bd5a0ad2ec3ea4046ab2",
 "version": "0.29.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
