"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lethean
from lethean.model.vpn_settings_entity import VpnSettingsEntity


class TestVpnSettingsEntity(unittest.TestCase):
    """VpnSettingsEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVpnSettingsEntity(self):
        """Test VpnSettingsEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VpnSettingsEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
