"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import lethean
from lethean.api.vpn_api import VpnApi  # noqa: E501


class TestVpnApi(unittest.TestCase):
    """VpnApi unit test stubs"""

    def setUp(self):
        self.api = VpnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_services(self):
        """Test case for list_services

        """
        pass


if __name__ == '__main__':
    unittest.main()
