"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lethean
from lethean.model.certificates_entity import CertificatesEntity


class TestCertificatesEntity(unittest.TestCase):
    """CertificatesEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCertificatesEntity(self):
        """Test CertificatesEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CertificatesEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
