# Generated by Django 3.2.5 on 2021-07-17 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c8fa38d8-25f0-440b-85e2-cfa51e4320fd'), editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
