# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: controller/service.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Optional

import betterproto

from ..service_stub import ServiceStub
from ..models import controller


class HealthCheckResponseServingStatus(betterproto.Enum):
    UNKNOWN = 0
    SERVING = 1
    NOT_SERVING = 2


@dataclass
class ExecuteEncryptedControllerJobRequest(betterproto.Message):
    job: controller.EncryptedControllerJob = betterproto.message_field(1)


@dataclass
class ExecuteEncryptedControllerJobResponse(betterproto.Message):
    job_id: str = betterproto.string_field(1)


@dataclass
class GetControllerJobResultsRequest(betterproto.Message):
    job_id: str = betterproto.string_field(1)


@dataclass
class GetControllerJobResultsResponse(betterproto.Message):
    result: controller.ControllerJobExecutionResult = betterproto.message_field(1)


@dataclass
class HealthCheckRequest(betterproto.Message):
    service: str = betterproto.string_field(1)


@dataclass
class HealthCheckResponse(betterproto.Message):
    status: "HealthCheckResponseServingStatus" = betterproto.enum_field(1)


class ControllerStub(ServiceStub):
    async def execute_encrypted_controller_job(
        self, *, job: Optional[controller.EncryptedControllerJob] = None
    ) -> ExecuteEncryptedControllerJobResponse:
        request = ExecuteEncryptedControllerJobRequest()
        if job is not None:
            request.job = job

        return await self._unary_unary(
            "/services.controller.Controller/ExecuteEncryptedControllerJob",
            request,
            ExecuteEncryptedControllerJobResponse,
        )

    async def get_controller_job_results(self, *, job_id: str = "") -> GetControllerJobResultsResponse:
        request = GetControllerJobResultsRequest()
        request.job_id = job_id

        return await self._unary_unary(
            "/services.controller.Controller/GetControllerJobResults",
            request,
            GetControllerJobResultsResponse,
        )
