
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-30T10:35:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "36d61715e56b55242f8c2b8f19901f6755c92ca0",
 "version": "1.83.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
