
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-25T20:01:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fdbe3788fd2ac7ce61749d9a7495a540c4097f8f",
 "version": "0.1.0a26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
