
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-27T16:31:34+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "004c5b872979d3b5473e58408ba803880dd43374",
 "version": "v0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
