[tool.poetry]
name = "acquisition_extractor"
version = "0.3.1"
description = "Parse statute, decision data from a specified location"
authors = ["Marcelino G. Veloso III <testmarcelino@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9.1"
PyYAML = "^5.4.1"
beautifulsoup4 = "^4.9.3"
html5lib = "^1.1"
arrow = "^1.1.0"


[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-instafail = "^0.4.2"
pytest-sugar = "^0.9.4"
pytest-icdiff = "^0.5"
pytest-cov = "^2.12.0"
mypy = "^0.902"
black = "^21.7b0"
isort = "^5.9.2"
pre-commit = "^2.13.0"
ipykernel = "^5.5.5"
tqdm = "^4.61.2"

[tool.pytest]
minversion = "6.0"
addopts = "-ra -q --cov=acquisition_extractor tests/"
testpaths = ["tests"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[tool.black]
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''


[build-system]
requires = ["poetry-core>=1.1.4"]
build-backend = "poetry.core.masonry.api"
