repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        language: system
        entry: bash -c "PYTHONPATH=$(pwd)/django_json_logging:$PYTHONPATH pipenv run mypy drf_health_check"
        pass_filenames: false
        verbose: true
        types: [ "python" ]