[tool.poetry]
name = "simple-sqla-timer"
version = "0.1.0"
description = "A simple way of logging how long it takes for SQLAlchemy queries to run."

authors = ["Saulius Beinorius <saulius.beinorius@gmail.com>"]
maintainers = ["Saulius Beinorius <saulius.beinorius@gmail.com>"]

license = "Apache-2.0"
readme = "README.md"

homepage = "https://github.com/Barbora-Data-Science/simple-sqla-timer"
repository = "https://github.com/Barbora-Data-Science/simple-sqla-timer"
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
SQLAlchemy = "^1.3.19"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
