#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pybancodobrasil']

package_data = \
{'': ['*']}

setup(name='pybancodobrasil',
      version='0.0.3',
      description='This module do web crawler of banco do brasil.',
      author='Guilherme Fabrin Franco',
      author_email='guilherme.fabrin@gmail.com',
      url='https://github.com/guifabrin/pybancodobrasil',
      packages=packages,
      package_data=package_data,
     )
