
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-29T15:55:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a57d9c69623bcefc8ed12f2bdda18c5c9d545ed6",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
