[tool.poetry]
name = "plc_main"
version = "1.0.0"
description = "Logical components in python."
authors = ["Your Name <you@example.com>"]
license = "none"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
