[build-system]
requires = [
    "pip==21.0.1",
    "setuptools==54.1.1",
    "wheel==0.36.2",
    "pyglet==1.5.17",
    "pillow==8.1.2",
    "moderngl==5.6.4",
    "moderngl-window==2.3.0",
]
build-backend = "setuptools.build_meta"