[tool.poetry]
name = "tsp_heuristics"
version = "0.2.0"
description = "Meta-heuristics for solving the TSP"
authors = ["Adriel Martins <adrielfalcao@gmail.com>"]
license = "The Unlicense"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.1"
matplotlib = "^3.4.2"
pandas = "^1.3.0"
sympy = "^1.8"
tsplib95 = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
