---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/collections.yml
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: centos-8
    image: centos:8
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
