[tool.poetry]
name = "tabby-connection-gateway"
version = "0.1.0"
description = ""
authors = ["Eugene Pankov <e@ajenti.org>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = {version = "^21.6b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
