[tool.poetry]
name = "poetry-git-version-changer"
description = "An extension to support dynamic package versioning with poetry."
license = "Apache-2.0"
authors = [
    "Bijij",
]
version = "1.0.0a"
readme = "README.md"
repository = "https://github.com/bijij/unnamed-poetry-extension"
keywords = ["poetry", "extension", "versioning"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Version Control",
    "Topic :: Software Development :: Version Control :: Git",
]
include = [
    "zzz_poetry_git_version_changer.py",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
black = "^21.7b0"

[tool.black]
line-length = 119
target-version = ["py38"]

[tool.pyright]
include = [
    "poetry_git_version_changer",
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"