[tool.poetry]
name = "robotnikmq"
version = "0.3.1"
description = "Utilities for safe, efficient, and scalable infrastructure using RabbitMQ"
authors = ["Eugene Kovalev <eugene@kovalev.systems>"]
classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
]
documentation="https://gitlab.com/robotnikmq/robotnikmq"
repository="https://gitlab.com/robotnikmq/robotnikmq"
readme="README.md"
license="GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"
typeguard = "^2.1.0"
pyyaml = "^5.4.1"
pydantic = "^1.7.3"
pika = "^1.2"
funcy = "^1.16"
arrow = "^1.1.1"
logzero = "^1.7.0"
retry = "^0.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.11.1"
pylint = "^2.6.0"
mypy = "^0.790"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
