# Generated by Django 3.2.5 on 2021-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('contact_type', models.CharField(choices=[('fab fa-vk', 'Вконтакте'), ('fab fa-facebook', 'Facebook'), ('fab fa-whatsapp', 'whatsApp'), ('fab fa-telegram', 'Telegram'), ('fab fa-instagram', 'Instagram'), ('fas fa-map-marker-alt', 'Геолокация')], max_length=50, verbose_name='Тип контакта')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DELETED', 'Deleted')], max_length=50, verbose_name='Статус контакта')),
                ('size', models.IntegerField(default=2, verbose_name='Размер')),
                ('style', models.CharField(default='', max_length=500, verbose_name='Дополнительный css стиль')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('extraclass', models.CharField(default='', max_length=500, verbose_name='Дополнительный класс для кастомизации')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
