[build-system]
requires = ['pip', 'setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-fem<=2.8.0.dev20210726', 'dune-alugrid<=2.8.0.dev20210726', 'matplotlib', 'triangle', 'scipy', 'sortedcontainers']
build-backend = 'setuptools.build_meta'
