[tool.poetry]
name = "deutschland"
version = "0.1.0"
description = ""
authors = ["Lilith Wittmann <mail@lilithwittmann.de>"]
packages = [
    { include = "*.py" },
]

[tool.poetry.dependencies]
python = "^3.7"
Shapely = "^1.7.1"
mapbox-vector-tile = "^1.2.1"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
