
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-02T08:43:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5aeb9b5885aae7c06d1b2377d19abd37648dcc70",
 "version": "1.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
