# Generated by Django 3.1.13 on 2021-07-26 20:56

import admin_kit.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genres', admin_kit.models.MultiSelectField(ajax_source='__sICgnZmljdGlvbmFsJywgJ2ZpY3Rpb25hbCcpLCAoJ2ZhbnRhc', ajax_source_in_multi_dep=None, ajax_subscribe=False, ajax_target=None, default_name=None, default_value=None, kit_config={'ajax_target': 'genres', 'default_name': 'id_genres'}, verbose_name='Valid Genres')),
                ('filteredGenres', admin_kit.models.SelectField(ajax_source=None, ajax_source_in_multi_dep=None, ajax_subscribe=False, ajax_target=None, blank=True, default_name=None, default_value=None, kit_config={'ajax-source': 'genres', 'ajax-subscribe': True, 'ajax-target': 'genres-desc', 'default_name': 'id_filtered_genres'})),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_ajax_duplicate.author')),
            ],
        ),
    ]
