# Generated by Django 3.1.13 on 2021-07-26 23:47

import admin_kit.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_ajax_duplicate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='filteredGenres',
            field=admin_kit.models.SelectField(ajax_source=None, ajax_source_in_multi_dep=None, ajax_subscribe=False, ajax_target=None, blank=True, default_name=None, default_value=None, kit_config={'ajax-source': 'filtered_genres', 'ajax-subscribe': True, 'ajax-target': 'genres-desc', 'default_name': 'id_filtered_genres'}),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=admin_kit.models.MultiSelectField(ajax_source='__S1maScpLCAoJ2ZpY3Rpb25hbCcsICdmaWN0aW9uYWwnKSwgKCd', ajax_source_in_multi_dep=None, ajax_subscribe=False, ajax_target=None, default_name=None, default_value=None, kit_config={'ajax-target': 'filtered_genres', 'default_name': 'id_genres'}, verbose_name='Valid Genres'),
        ),
    ]
