[tool.poetry]
name = "sloth-ci-ext-notifications"
version = "1.0.8"
description = "Email notifications for Sloth CI builds"
authors = ["Constantine Molchanov <moigagoo@live.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "sloth_ci_ext_notifications.py"}]

[tool.poetry.dependencies]
python = "^3.9"
sloth-ci = "^2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
