name: qa4sm_reader
channels:
- defaults
- conda-forge
dependencies:
- xarray
- netcdf4
- pandas
- numpy
- matplotlib
- cartopy
- h5netcdf
- pip
- pip:
    - parse
    - colorcet
    - seaborn
    - pygeogrids
    - pytest
    - pytest-cov
