[tool.poetry]
name = "sdmn"
version = "0.1.2"
description = "Quickstart your masternode"
readme = "README.md"
license = "GPL-3.0+"
homepage = "https://swapdex.net"
repository = "https://github.com/69th-byte/sdmn"
documentation = "https://docs.swapdex.net/masternode/sdmn/"
keywords = ["smartdex", "blockchain", "masternode", "node"]
authors = [
  "Etienne Napoleone <info@swapdex.net>"
]

[tool.poetry.dependencies]
python = "^3.5"
docker = "^3.5.0"
pastel = "^0.1.0"
clint = "^0.5.1"
python-slugify = "^1.2"
click = "^7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.5"
coveralls = "^1.3"
pytest = "^3.6"

[tool.poetry.scripts]
sdmn = "sdmn.sdmn:main"
