
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9c8dd395a8ed91547c923e8cc56b48814b587fec",
 "version": "7.6.2pre11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
