
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-30T21:02:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec5b5b6d88f105510b6427a4489ee2471c729290",
 "version": "v0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
