
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-27T04:05:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "90fe0d9dac959643ccab3c5be15024d4402f6de9",
 "version": "4.7.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
