
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-26T08:06:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2132ab44b9718d102a52926d06a7ff4dfa541817",
 "version": "0.53.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
