#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['read_toml']

package_data = \
{'': ['*']}

extras_require = \
{":python_version<'3.6'": ['toml'],
 ":python_version>='3.6'": ['tomli >=1.1.0'],
 'test': ['pytest',
          'pytest-forward-compatability',
          'pytest-cov',
          'coverage>=5.3']}

setup(name='read_toml',
      version='0.0.0a0',
      description='read_toml paths',
      author='Thomas Grainger',
      author_email='read-toml@graingert.co.uk',
      url='https://github.com/graingert/read-toml',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
     )
