# Generated by Django 3.2.5 on 2021-07-26 18:06

import ckeditor_uploader.fields
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REVIEW', 'Рассмотрение'), ('ACTIVE', 'Действующий'), ('DELETED', 'Удалено'), ('REFUSED', 'Отклонено')], help_text='Статус', max_length=30, verbose_name='Статус')),
                ('source', models.URLField(default='yandex.com', verbose_name='Источник')),
                ('post_date', models.DateTimeField(verbose_name='Дата поста')),
                ('post_header', models.CharField(default='Заголовок', max_length=100, verbose_name='Заголовок')),
                ('post_content_preview', models.CharField(default='Краткое содержание', max_length=300, verbose_name='Краткое содержание')),
                ('post_content', ckeditor_uploader.fields.RichTextUploadingField(default='Содержание', verbose_name='Содержание поста')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='image')),
            ],
        ),
    ]
