
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-29T10:15:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e6ffd9e7c5d78260feeedf52351dcd7f16449e4",
 "version": "1.4.1rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
