"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.7
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lethean
from lethean.model.ecdh_info import EcdhInfo
globals()['EcdhInfo'] = EcdhInfo
from lethean.model.raw_transaction_rct_signature import RawTransactionRctSignature


class TestRawTransactionRctSignature(unittest.TestCase):
    """RawTransactionRctSignature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRawTransactionRctSignature(self):
        """Test RawTransactionRctSignature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RawTransactionRctSignature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
