"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.7
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import unittest

import lethean
from lethean.api.explorer_api import ExplorerApi  # noqa: E501


class TestExplorerApi(unittest.TestCase):
    """ExplorerApi unit test stubs"""

    def setUp(self):
        self.api = ExplorerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_block(self):
        """Test case for get_block

        """
        pass

    def test_get_emission(self):
        """Test case for get_emission

        """
        pass

    def test_get_mempool(self):
        """Test case for get_mempool

        """
        pass

    def test_get_network_info(self):
        """Test case for get_network_info

        """
        pass

    def test_get_outputs_blocks(self):
        """Test case for get_outputs_blocks

        """
        pass

    def test_get_raw_block_data(self):
        """Test case for get_raw_block_data

        """
        pass

    def test_get_raw_transaction_data(self):
        """Test case for get_raw_transaction_data

        """
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        """
        pass

    def test_get_transactions(self):
        """Test case for get_transactions

        """
        pass

    def test_get_version(self):
        """Test case for get_version

        """
        pass

    def test_prove_transfer(self):
        """Test case for prove_transfer

        """
        pass

    def test_search_chain(self):
        """Test case for search_chain

        """
        pass


if __name__ == '__main__':
    unittest.main()
