"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.7
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lethean
from lethean.model.raw_block_miner_vin import RawBlockMinerVin
from lethean.model.raw_block_miner_vout import RawBlockMinerVout
from lethean.model.rct_sig_entity import RctSigEntity
globals()['RawBlockMinerVin'] = RawBlockMinerVin
globals()['RawBlockMinerVout'] = RawBlockMinerVout
globals()['RctSigEntity'] = RctSigEntity
from lethean.model.raw_block_miner_tx import RawBlockMinerTx


class TestRawBlockMinerTx(unittest.TestCase):
    """RawBlockMinerTx unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRawBlockMinerTx(self):
        """Test RawBlockMinerTx"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RawBlockMinerTx()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
