"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.7
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lethean
from lethean.model.emission_entity import EmissionEntity


class TestEmissionEntity(unittest.TestCase):
    """EmissionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmissionEntity(self):
        """Test EmissionEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmissionEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
