"""
    Lethean VPN

    Distributed Virtual Private Marketplace  # noqa: E501

    The version of the OpenAPI document: 1.0.7
    Contact: contact@lethean.io
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lethean
from lethean.model.raw_transaction_entity_vout_target import RawTransactionEntityVoutTarget
globals()['RawTransactionEntityVoutTarget'] = RawTransactionEntityVoutTarget
from lethean.model.raw_transaction_entity_vout import RawTransactionEntityVout


class TestRawTransactionEntityVout(unittest.TestCase):
    """RawTransactionEntityVout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRawTransactionEntityVout(self):
        """Test RawTransactionEntityVout"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RawTransactionEntityVout()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
