[package]
name = "tabular_entropy"
version = "0.1.1"
authors = ["Lissa Hyacinth <lissahyacinth@gmail.com>"]
edition = "2018"
description = "Calculate Mutual Information for Paired Vectors"
license = "GNU LGPLv3"
repository = "https://github.com/lissahyacinth/mutual_information/"

[dependencies]
pyo3 = { version = "0.14.0", features = ["extension-module"] }
itertools = "0.10.1"

[dev-dependencies]
proptest = "1.0.0"

[lib]
name = "tabular_entropy"
crate-type = ["cdylib"]