
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-27T07:53:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d99aca6d8add9418c09008673a63499ebb79bc09",
 "version": "0.29.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
