[tool.poetry]
name = "apitestbasic"
version = "2.0.0"
description = ""
authors = ["lin"]

[tool.poetry.dependencies]
python = "^3.9"
sgqlc = "^13.0"
pytest = "^6.2.4"
jmespath = "^0.10.0"
PyHamcrest = "^2.0.2"
python-utils = "^2.5.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
