
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-07-28T16:41:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f552e35b86b05f372a374fb397c8f49595eab8cf",
 "version": "v2.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
