[tool.poetry]
name = "blackdogosint"
version = "0.1.42"
description = "api supporting OSINT open source queries"
authors = ["darkcode357 <darkcode357@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
Django = "^3.2.4"
standalone = "^1.0.1"
requests = "^2.25.1"
google = "^3.0.0"
selenium = "^3.141.0"
Pillow = "^8.2.0"
isort = {extras = ["requirements_deprecated_finder", "pipfile_deprecated_finder"], version = "^5.9.1"}
importanize = "^0.7.0"
import-linter = "^1.2.1"
types-freezegun = "^0.1.4"
types-tabulate = "^0.1.1"
types-pytz = "^2021.1.0"
types-pathlib2 = "^0.1.6"
types-six = "^0.1.7"
types-orjson = "0.1.1"
types-pynamodb = "^0.1"
osint = "^0.5"
pytype = "^2021.6.17"
pyright = "^0.0.2"
search-engine-parser = "^0.6.2"
toml = "^0.10.2"
six = "^1.16.0"
socks = "^0"
PySocks = "^1.7.1"
colored-traceback = "^0.3.0"
mkdocs = "^1.2.1"
mkdocs-material = "^7.1.9"
mkdocs-bootswatch = "^1.1"
aiodns = "3.0.0"
flake8 = "3.9.2"
mypy = "0.910"
mypy-extensions = "0.4.3"
pyflakes = "2.3.1"
pytest-asyncio = "0.15.1"
types-certifi = "0.1.4"
types-chardet = "0.1.3"
types-PyYAML = "5.4.3"
types-requests = "0.1.11"
aiosqlite = "^0.17.0"
slowapi = "^0.1.4"
fastapi = "0.66.0"
shodan = "^1.25.0"
Proxy-List-Scrapper = "^0.2.2"
SQLAlchemy = "^1.4.21"
Flask-SQLAlchemy = "^2.5.1"
pwn = "^1.0"
tabulate = "^0.8.9"
docker = "^5.0.0"
certifi = "^2021.5.30"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.13.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
