CHUNK_UPLOAD_SIZE = 600000 #600K
IMG_UPLD_PREFIX_URL = 'http://localhost:5000/api/'
BASE_IMG_UPLD_URL = IMG_UPLD_PREFIX_URL + 'Upload/'
ACCT_MGMT_PREFIX_URL = 'http://localhost:5010/api/'
BASE_ACCT_MGMT_URL = ACCT_MGMT_PREFIX_URL + 'account/'
BASE_USR_PROF_MGMT_URL = ACCT_MGMT_PREFIX_URL + 'userprofile/'