SFDC_OBJECT = "SFDC Object"
SFDC_FIELD = "SFDC Field"
SFDC_DATA_TYPE = "SFDC Data Type"
JSON_PATH = "JSONPath"
COMMENT = "Comment"

ALL = [SFDC_OBJECT, SFDC_FIELD, SFDC_DATA_TYPE, JSON_PATH, COMMENT]
